// Checks the stock icons in public/tokens and writes lib/token-icons.generated.ts (the tickers that have a file).
// Usage: pnpm tokens:icons            (checks public/tokens, writes the generated set)
//        node scripts/token-icons.mjs --check <dir>   (checks a directory only, writes nothing)
// No image library is needed: the PNG and WebP headers hold the pixel size.
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const MIN_SIZE = 128;
export const MAX_SIZE = 512;
export const MAX_BYTES = 10 * 1024;
export const NAME_RE = /^[A-Z0-9.]{1,10}\.(png|webp)$/;

/** Pixel size read from a PNG or WebP header, or null when the file is neither. */
export function imageSize(buf) {
  if (buf.length >= 24 && buf.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])))
    return { type: "png", width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
  if (
    buf.length >= 30 &&
    buf.toString("ascii", 0, 4) === "RIFF" &&
    buf.toString("ascii", 8, 12) === "WEBP"
  ) {
    const kind = buf.toString("ascii", 12, 16);
    if (kind === "VP8X")
      return { type: "webp", width: 1 + buf.readUIntLE(24, 3), height: 1 + buf.readUIntLE(27, 3) };
    if (kind === "VP8L") {
      const b = buf.readUInt32LE(21);
      return { type: "webp", width: 1 + (b & 0x3fff), height: 1 + ((b >> 14) & 0x3fff) };
    }
    if (kind === "VP8 ")
      return {
        type: "webp",
        width: buf.readUInt16LE(26) & 0x3fff,
        height: buf.readUInt16LE(28) & 0x3fff,
      };
  }
  return null;
}

/** Every problem found in a folder of icons, and the tickers of the good files. */
export function checkIcons(dir) {
  const problems = [];
  const files = {};
  if (!existsSync(dir)) return { problems, files };
  for (const name of readdirSync(dir).sort()) {
    if (name === "SOURCES.md" || name.startsWith(".")) continue;
    const path = join(dir, name);
    if (!statSync(path).isFile()) continue;
    const bad = [];
    if (!NAME_RE.test(name))
      bad.push("name must look like NVDA.png (uppercase ticker, png or webp)");
    const buf = readFileSync(path);
    if (buf.length > MAX_BYTES) bad.push(`${buf.length} bytes is over ${MAX_BYTES}`);
    const size = imageSize(buf);
    if (!size) bad.push("not a PNG or WebP file");
    else {
      // Square, at least 128 px (sharp at 3x for the 40 px slots) and at most 512; the 10 KB cap keeps the weight down either way.
      if (size.width !== size.height || size.width < MIN_SIZE || size.width > MAX_SIZE)
        bad.push(
          `${size.width} x ${size.height} must be square, ${MIN_SIZE} to ${MAX_SIZE} px (128 x 128 is best)`,
        );
      const ext = name.split(".").pop();
      if (ext !== size.type) bad.push(`extension .${ext} does not match the ${size.type} content`);
    }
    if (bad.length) problems.push(`${name}: ${bad.join("; ")}`);
    else files[name.replace(/\.[a-z]+$/, "")] = name;
  }
  return { problems, files };
}

export function generatedSource(files) {
  const entries = Object.entries(files)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([ticker, file]) =>
        `  ${/^[A-Za-z_$][\w$]*$/.test(ticker) ? ticker : JSON.stringify(ticker)}: ${JSON.stringify(file)},`,
    )
    .join("\n");
  return `// Generated by scripts/token-icons.mjs (pnpm tokens:icons). Do not edit: the tickers that have a file in public/tokens.\nexport const TOKEN_ICON_FILES: Readonly<Record<string, string>> = {\n${entries}\n};\n`;
}

const here = dirname(fileURLToPath(import.meta.url));
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const checkOnly = process.argv[2] === "--check";
  const dir = checkOnly ? process.argv[3] : join(here, "../public/tokens");
  const { problems, files } = checkIcons(dir);
  if (problems.length) {
    console.error(`Token icons: ${problems.length} problem(s)\n- ${problems.join("\n- ")}`);
    process.exit(1);
  }
  if (!checkOnly) {
    const out = join(here, "../lib/token-icons.generated.ts");
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, generatedSource(files));
  }
  console.log(`Token icons: ${Object.keys(files).length} file(s) OK`);
}
