// Generated by contracts/tools/gen_buyable.py from contracts/deploy/assets.json.
// Planned target: import into the product only after list_enabled.py passes.
export const GENERATED_BUYABLE_TICKERS = [
  {
    ticker: "AAPL",
    name: "Apple Inc.",
  },
  {
    ticker: "AMZN",
    name: "Amazon.Com Inc",
  },
  {
    ticker: "BABA",
    name: "Alibaba Group Holding Limited",
  },
  {
    ticker: "BMNR",
    name: "Bitmine Immersion Technologies, Inc.",
  },
  {
    ticker: "CRCL",
    name: "Circle Internet Group, Inc.",
  },
  {
    ticker: "GME",
    name: "GameStop Corp.",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc.",
  },
  {
    ticker: "HOOD",
    name: "Robinhood Markets, Inc.",
  },
  {
    ticker: "INTC",
    name: "Intel Corp",
  },
  {
    ticker: "META",
    name: "Meta Platforms, Inc.",
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corp",
  },
  {
    ticker: "MSTR",
    name: "Strategy Inc",
  },
  {
    ticker: "NFLX",
    name: "NetFlix Inc",
  },
  {
    ticker: "NVDA",
    name: "Nvidia Corp",
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
  },
  {
    ticker: "SKHY",
    name: "SK Hynix",
  },
  {
    ticker: "SNDK",
    name: "SanDisk",
  },
  {
    ticker: "SPCX",
    name: "SpaceX",
  },
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF Trust",
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
  },
  {
    ticker: "TSM",
    name: "Taiwan Semiconductor Manufacturing Co Ltd.",
  },
] as const;

export const GENERATED_BUYABLE_ASSETS = [
  {
    symbol: "SPCXB",
    ticker: "SPCX",
    address: "0xbe9d156892e55e7154bcd3cb0fea677f9d3103e1",
    kind: "bstock",
  },
  {
    symbol: "BABAB",
    ticker: "BABA",
    address: "0x4ef9d3062c7f6eba4aae4990c5036598c6eff4ec",
    kind: "bstock",
  },
  {
    symbol: "GOOGLB",
    ticker: "GOOGL",
    address: "0x3f53de71c126bdabae20f9cd64848d317f6c3238",
    kind: "bstock",
  },
  {
    symbol: "SKHYB",
    ticker: "SKHY",
    address: "0xca750ef65f295bbecd685abf54e82caf297bdb61",
    kind: "bstock",
  },
  {
    symbol: "MSTRB",
    ticker: "MSTR",
    address: "0xe87afb3076aeb0f9b14e368de8145ae6a2826a14",
    kind: "bstock",
  },
  {
    symbol: "CRCLB",
    ticker: "CRCL",
    address: "0x80f3d493ebce97e343c53d29a137942416b4ffc0",
    kind: "bstock",
  },
  {
    symbol: "SNDKB",
    ticker: "SNDK",
    address: "0x3ee4df61bd4f867e349beae8bfe07bc31b4850fb",
    kind: "bstock",
  },
  {
    symbol: "HOODB",
    ticker: "HOOD",
    address: "0xa394dcea3fd3847fd793afbfd163e2e3858b7c65",
    kind: "bstock",
  },
  {
    symbol: "MSFTB",
    ticker: "MSFT",
    address: "0x80106cb3ead06659a5ad19df39d9b4733863b9b0",
    kind: "bstock",
  },
  {
    symbol: "INTCB",
    ticker: "INTC",
    address: "0xe614e2fc6c787035ff51f452e8e826bfd32d5283",
    kind: "bstock",
  },
  {
    symbol: "METAB",
    ticker: "META",
    address: "0x7425889fe94f9d693e8daefe88bcced6acfef4c0",
    kind: "bstock",
  },
  {
    symbol: "TSMB",
    ticker: "TSM",
    address: "0xab78b89b5bb00236be0b4b20704cbfa04efc711c",
    kind: "bstock",
  },
  {
    symbol: "SPCXon",
    ticker: "SPCX",
    address: "0xd0a58bc9d88d3ff48c0294cb7e45937d0e41a928",
    kind: "ondo",
  },
  {
    symbol: "GMEon",
    ticker: "GME",
    address: "0xdabb9aff4cf02f26d2014e4ca9f94ac6fe6572a3",
    kind: "ondo",
  },
  {
    symbol: "GOOGLon",
    ticker: "GOOGL",
    address: "0x091fc7778e6932d4009b087b191d1ee3bac5729a",
    kind: "ondo",
  },
  {
    symbol: "CRCLon",
    ticker: "CRCL",
    address: "0x992879cd8ce0c312d98648875b5a8d6d042cbf34",
    kind: "ondo",
  },
  {
    symbol: "AMZNon",
    ticker: "AMZN",
    address: "0x4553cfe1c09f37f38b12dc509f676964e392f8fc",
    kind: "ondo",
  },
  {
    symbol: "BMNRon",
    ticker: "BMNR",
    address: "0x52ad57a7ea642e99a892afc79e937b383f1b59e9",
    kind: "ondo",
  },
  {
    symbol: "TSMon",
    ticker: "TSM",
    address: "0xc37042a7a4fa510d8884a433762ab87257b91965",
    kind: "ondo",
  },
  {
    symbol: "NFLXon",
    ticker: "NFLX",
    address: "0x7048f5227b032326cc8dbc53cf3fddd947a2c757",
    kind: "ondo",
  },
  {
    symbol: "NVDAB",
    ticker: "NVDA",
    address: "0x02fca66c1d1afb4e2a7884261eb00f63598a7436",
    kind: "bstock",
  },
  {
    symbol: "NVDAon",
    ticker: "NVDA",
    address: "0xa9ee28c80f960b889dfbd1902055218cba016f75",
    kind: "ondo",
  },
  {
    symbol: "AAPLB",
    ticker: "AAPL",
    address: "0x431a3bee82e2ca41e49895cbece5bb0f76a89b7a",
    kind: "bstock",
  },
  {
    symbol: "AAPLon",
    ticker: "AAPL",
    address: "0x390a684ef9cade28a7ad0dfa61ab1eb3842618c4",
    kind: "ondo",
  },
  {
    symbol: "TSLAB",
    ticker: "TSLA",
    address: "0x5b1910eaad6450e50f816082aa078c41f10c292f",
    kind: "bstock",
  },
  {
    symbol: "TSLAon",
    ticker: "TSLA",
    address: "0x2494b603319d4d9f9715c9f4496d9e0364b59d93",
    kind: "ondo",
  },
  {
    symbol: "QQQB",
    ticker: "QQQ",
    address: "0x205812cdbed920aff76c6580abd681a46d11efc7",
    kind: "bstock",
  },
  {
    symbol: "QQQon",
    ticker: "QQQ",
    address: "0x0cde6936d305d5b34667fc46425e852efd73559a",
    kind: "ondo",
  },
  {
    symbol: "SPYB",
    ticker: "SPY",
    address: "0x7138b48df7d98d7e3cc221bfe7192d0a178182d8",
    kind: "bstock",
  },
  {
    symbol: "SPYon",
    ticker: "SPY",
    address: "0x6a708ead771238919d85930b5a0f10454e1c331a",
    kind: "ondo",
  },
] as const;

export const GENERATED_BUYABLE_ISSUERS = {
  AAPL: ["bstock", "ondo"],
  AMZN: ["ondo"],
  BABA: ["bstock"],
  BMNR: ["ondo"],
  CRCL: ["bstock", "ondo"],
  GME: ["ondo"],
  GOOGL: ["bstock", "ondo"],
  HOOD: ["bstock"],
  INTC: ["bstock"],
  META: ["bstock"],
  MSFT: ["bstock"],
  MSTR: ["bstock"],
  NFLX: ["ondo"],
  NVDA: ["bstock", "ondo"],
  QQQ: ["bstock", "ondo"],
  SKHY: ["bstock"],
  SNDK: ["bstock"],
  SPCX: ["bstock", "ondo"],
  SPY: ["bstock", "ondo"],
  TSLA: ["bstock", "ondo"],
  TSM: ["bstock", "ondo"],
} as const;
